const screen=document.querySelector('#screen');
const toast=document.querySelector('#toast');
const device=document.querySelector('#device');
const storeKey='xiaohei-figma-demo-records-v2';
const sample=[
 {id:'seed-salary',type:'income',category:'工资',categoryId:'income-salary',amount:100,account:'微信',date:'2026-09-30',time:'17:57'},
 {id:'seed-dinner',type:'expense',category:'餐饮',categoryId:'daily-0',amount:300,note:'请人吃饭预算',date:'2026-09-30',time:'15:10'},
 {id:'seed-breakfast',type:'expense',category:'早餐',categoryId:'food-breakfast',amount:58,account:'支付宝',date:'2026-09-30',time:'10:29'},
 {id:'seed-delivery',type:'expense',category:'餐饮',categoryId:'daily-0',amount:23.48,note:'饿了么',date:'2026-09-30',time:'09:01'},
 {id:'seed-bread',type:'expense',category:'餐饮',categoryId:'daily-0',amount:4.5,note:'巴比文汇路六店',date:'2026-09-30',time:'06:47'},
 {id:'seed-income',type:'income',category:'工资',categoryId:'income-salary',amount:2000,account:'微信',date:'2026-09-28',time:'18:00'},
 ...[{amount:30,time:'19:00'},{amount:25,time:'12:00'},{amount:26.8,time:'08:00'}].map((r,i)=>({...r,id:'seed-food-'+i,type:'expense',category:'餐饮',categoryId:'daily-0',date:'2026-09-29'})),
 {id:'seed-invest',type:'expense',category:'投资',categoryId:'income-invest',amount:100,date:'2026-09-29',time:'15:00'},
 {id:'seed-shop',type:'expense',category:'购物',categoryId:'daily-5',amount:33.9,date:'2026-09-29',time:'10:00'},
 ...[{amount:0.25,time:'12:00'},{amount:0.5,time:'08:00'}].map((r,i)=>({...r,id:'seed-food-small-'+i,type:'expense',category:'餐饮',categoryId:'daily-0',date:'2026-09-28'})),
 {id:'seed-other',type:'expense',category:'其他支出',categoryId:'daily-other',amount:25.35,date:'2026-09-28',time:'07:00'}
];
let added=[];try{const value=JSON.parse(localStorage.getItem(storeKey)||'[]');if(Array.isArray(value))added=value;if(!localStorage.getItem(storeKey)){const old=JSON.parse(localStorage.getItem('heihei-demo-bills-v1')||'[]');if(Array.isArray(old))added=old.filter(r=>![1,2,3,4].includes(r.id)).map(r=>({...r,id:String(r.id),time:r.time||'12:08'}));if(added.length)localStorage.setItem(storeKey,JSON.stringify(added))}}catch{}
let scene='home',previous='home',entryType='expense',entryCategory='餐饮',entryCategoryChosen=false,entryAccount='账户',entryNumber='',entryMemo='',entryDate='2025-09-02',filter='全部',statPeriod='本月',searchText='',selectedRecord=null;
const categoryNames=['餐饮','零食','水果','饮品','做饭食材'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categoryArt={餐饮:'food',零食:'snack',水果:'fruit',饮品:'drink',做饭食材:'vegetable'};
const categoryFallback={工资:'💼',奖金:'🎁',红包:'🧧',理财:'💰',其他:'✨',笔记:'✎',还款:'🪙',手动调整:'💴'};
function categoryIcon(record){const name=String(record.category||'').split('-')[0],art=categoryArt[name];return art?'<span class="category-icon category-icon--'+art+'" aria-hidden="true"></span>':'<span class="category-icon category-icon--fallback" aria-hidden="true">'+(categoryFallback[name]||'🧾')+'</span>'}
function categoryPill(record){return '<span class="record-category'+(record.type==='income'?' record-category--income':'')+'"><span>'+esc(record.category)+'</span>'+categoryIcon(record)+'</span>'}
const cash=n=>(Number(n)<0?'-':'')+'¥'+Math.abs(Number(n)).toFixed(2);
const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
function message(s){toast.textContent=s;toast.classList.add('on');clearTimeout(message.timer);message.timer=setTimeout(()=>toast.classList.remove('on'),1800)}
function go(name){previous=scene;scene=name;render()}
function back(){scene=previous||'home';render()}
function hit(label,x,y,w,h,fn){const b=document.createElement('button');b.className='hit';b.type='button';b.setAttribute('aria-label',label);b.title=label;Object.assign(b.style,{left:x+'%',top:y+'%',width:w+'%',height:h+'%'});b.addEventListener('click',fn);screen.appendChild(b);return b}
function art(src,alt=''){screen.innerHTML='<img class="art" src="./assets/'+src+'" alt="'+esc(alt)+'">'}
function onHome(){art('home.png','小黑记账首页');hit('打开侧边菜单',2,6.1,13,7.5,()=>go('drawer'));hit('图表分析',70,14,27,5,()=>go('stats'));hit('选择月份',20,13.4,43,5,()=>go('calendar'));hit('切换首页卡片',40,35.8,20,3,()=>go('budget'));hit('切换账本',76,40.5,21,5,()=>go('ledger'));hit('搜索',3.5,89.5,14.5,7,()=>go('search'));hit('手动记账',20,89.5,11,7,()=>openEntry());hit('一句话记账',32,89.5,52,7,()=>openEntry());hit('语音记账',84,89.5,13,7,()=>go('voice'));hit('查看支出详情',17,47.4,82,11,()=>detail(sample[0]));hit('查看笔记',16,59.5,82,14,()=>detail(sample[1]));hit('查看收入详情',16,74.5,82,11.5,()=>detail(sample[2]));if(added.length){const panel=document.createElement('div');panel.className='dynamic-home';panel.innerHTML='<div class="dynamic-home-head">最新记录</div>'+added.map((r,i)=>'<div class="new-record" data-i="'+i+'"><span class="time">'+esc(r.time)+'</span>'+categoryPill(r)+'<span class="value '+r.type+'">'+(r.type==='income'?'+':'−')+cash(r.amount)+'</span></div><small>'+esc(r.note||r.account||'')+'</small>').join('');screen.appendChild(panel);panel.querySelectorAll('[data-i]').forEach(el=>el.addEventListener('click',()=>detail(added[Number(el.dataset.i)])))}}
function onDrawer(){art('drawer.png','小黑记账侧边菜单');hit('关闭菜单',68,0,32,100,()=>go('home'));hit('个人信息',3,5.5,64,6.5,()=>go('profile'));hit('记录日历',3,13,63,21,()=>go('calendar'));const opts=[['图表统计','stats',7,41,19,6],['自动记账','auto',26,41,19,6],['导入导出','transfer',46,41,19,6],['我的资产','assets',7,47,19,6],['我的账单','ledger',26,47,19,6],['分类管理','categories',46,47,19,6],['我的物品','items',7,53,19,6],['社区公约','community',3,63,63,5],['关于我们','about',3,69,63,5],['设置','settings',3,74,63,5]];opts.forEach(([name,target,x,y,w,h])=>hit(name,x,y,w,h,()=>go(target)))}
function openEntry(){entryType='expense';entryCategory='餐饮';entryCategoryChosen=false;entryAccount='账户';entryNumber='';entryMemo='';entryDate='2025-09-02';go('entry')}
function onEntry(){art('entry.png','手动记账弹层');hit('关闭记账',0,0,100,26,()=>go('home'));hit('支出',3,28.4,16,5.5,()=>selectEntryType('expense'));hit('收入',20,28.4,16,5.5,()=>selectEntryType('income'));hit('笔记模式',69,28.4,29,5.5,()=>go('note'));const xs=[5.3,24.2,43.1,62,81.1];categoryNames.forEach((name,i)=>hit(name,xs[i],35.5,15,10,()=>{entryCategory=name;go('category')}));hit('账户',4,46.6,18,5,()=>go('accounts'));hit('默认账本',23,46.6,24,5,()=>go('ledgers'));hit('日期',49.5,46.6,21,5,()=>{const d=document.querySelector('#date-picker');if(d)d.showPicker?.()||d.click()});hit('计入收支',72.5,46.6,25,5,()=>message('已计入收支'));hit('填写备注',4,61.2,69,6,()=>{let input=document.querySelector('#entry-memo');if(!input){input=document.createElement('input');input.className='memo-only';input.id='entry-memo';input.placeholder='点击填写备注信息';input.setAttribute('aria-label','备注信息');input.addEventListener('input',e=>entryMemo=e.target.value);screen.appendChild(input)}input.focus()});hit('添加图片',74,61.5,12,6,()=>message('图片上传仅在正式应用中可用'));hit('拍照',85,61.5,12,6,()=>message('相机仅在正式应用中可用'));
const keyLabels=['1','2','3','⌫','4','5','6','+','7','8','9','−','再记','0','.','完成'];for(let i=0;i<16;i++){const col=i%4,row=Math.floor(i/4);hit(keyLabels[i],3.3+col*23.5,68.1+row*6.68,22.5,5.7,()=>tapKey(keyLabels[i]))}drawEntryCover()}
function selectEntryType(type){entryType=type;entryCategory=type==='income'?'工资':'餐饮';entryCategoryChosen=false;entryNumber='';render()}
function drawEntryCover(){document.querySelectorAll('.amount-only,.memo-only,.done-on,.selected-category,.entry-date,#date-picker,.income-pane').forEach(n=>n.remove());
  if(entryType==='income'){const pane=document.createElement('div');pane.className='income-pane';pane.innerHTML='<div class="income-tabs"><button id="expense-tab">支出</button><button class="active">收入</button><span>⇄ 笔记模式</span></div><div class="income-cats"></div>';screen.appendChild(pane);pane.querySelector('#expense-tab').addEventListener('click',()=>selectEntryType('expense'));pane.querySelector('.income-tabs span').addEventListener('click',()=>go('note'));const names=[['工资','💼'],['奖金','🎁'],['红包','🧧'],['理财','💰'],['其他','✨']];const row=pane.querySelector('.income-cats');names.forEach(([name,icon])=>{const btn=document.createElement('button');btn.className=entryCategory===name?'active':'';btn.innerHTML='<i>'+icon+'</i><span>'+name+'</span>';btn.addEventListener('click',()=>{entryCategory=name;drawEntryCover()});row.appendChild(btn)})}
  if(entryType==='expense'&&entryCategoryChosen){const idx=categoryNames.indexOf(entryCategory);if(idx>=0){const ring=document.createElement('div');ring.className='selected-category';ring.style.left=(5.3+idx*18.9)+'%';screen.appendChild(ring)}}
  if(entryNumber){const amount=document.createElement('div');amount.className='amount-only';amount.textContent=cash(numericValue());screen.appendChild(amount)}
  if(entryMemo){const input=document.createElement('input');input.className='memo-only';input.id='entry-memo';input.setAttribute('aria-label','备注信息');input.value=entryMemo;input.addEventListener('input',e=>entryMemo=e.target.value);screen.appendChild(input)}
  if(entryNumber&&numericValue()>0){const done=document.createElement('button');done.className='done-on';done.textContent='完成';done.addEventListener('click',saveRecord);screen.appendChild(done)}
  const d=document.createElement('input');d.type='date';d.id='date-picker';d.value=entryDate;d.style.cssText='position:absolute;left:50%;top:48%;width:1px;height:1px;opacity:0;z-index:5';d.addEventListener('change',e=>{entryDate=e.target.value;message('日期已选择')});screen.appendChild(d)}
function categoryExpanded(){art('category-expanded.png','记账分类展开');hit('关闭分类',0,0,100,11,()=>go('entry'));const xs=[4,23,42,61,80];for(let row=-1;row<2;row++){categoryNames.forEach((name,i)=>hit(name,xs[i],row<0?20.2:33.7+row*11.2,16,10,()=>{entryCategory=name;entryCategoryChosen=true;scene='entry';render()}))}}

function tapKey(k){if(k==='完成'){saveRecord();return}if(k==='再记'){entryNumber='';entryMemo='';drawEntryCover();return}if(k==='⌫'){entryNumber=entryNumber.slice(0,-1)}else if(k==='+'||k==='−'){if(!entryNumber||/[+−]$/.test(entryNumber))return;entryNumber+=k}else if(k==='.') {if(!entryNumber)entryNumber='0.';else if(!entryNumber.split(/[+−]/).at(-1).includes('.'))entryNumber+='.'}else if(/^\d$/.test(k)){if(entryNumber.length<12)entryNumber+=k}drawEntryCover()}
function numericValue(){const pieces=entryNumber.split(/([+−])/),first=Number(pieces[0]||0);if(pieces.length<3)return first;const second=Number(pieces[2]||0);return pieces[1]==='+'?first+second:first-second}
function saveRecord(){const value=numericValue();if(!value||value<=0){message('请输入金额');return}const d=new Date();const record={id:'record-'+Date.now(),type:entryType,category:entryCategory,amount:value,note:entryMemo,account:entryAccount,date:entryDate,time:[d.getHours(),d.getMinutes()].map(v=>String(v).padStart(2,'0')).join(':')};added.unshift(record);localStorage.setItem(storeKey,JSON.stringify(added));scene='home';render();message('记录成功')}
function page(title,body){screen.innerHTML='<div class="page"><div class="statusbar"><span>9:41</span><span class="system-icons"><svg width="67" height="16" viewBox="0 0 67 16" aria-hidden="true"><rect x="0" y="10" width="3" height="6" rx="1"/><rect x="5" y="7" width="3" height="9" rx="1"/><rect x="10" y="4" width="3" height="12" rx="1"/><rect x="15" y="1" width="3" height="15" rx="1"/><path d="M26 5Q34 -2 42 5M29 8Q34 3 39 8M32 11Q34 9 36 11" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/><rect x="47" y="2" width="18" height="12" rx="3" fill="none" stroke="currentColor" stroke-width="1.5"/><rect x="49" y="4" width="14" height="8" rx="1"/><rect x="66" y="6" width="1" height="4" rx="0.5"/></svg></span></div><header class="page-head"><button class="back" aria-label="返回">‹</button><span>'+esc(title)+'</span></header><div class="page-body">'+body+'</div></div>';screen.querySelector('.back').addEventListener('click',back)}
function stats(){const records=[...added,...sample].filter(r=>r.type!=='note');let expense=369+added.filter(r=>r.type==='expense'&&!r.operation).reduce((n,r)=>n+r.amount,0),income=844+added.filter(r=>r.type==='income'&&!r.operation).reduce((n,r)=>n+r.amount,0);page('图表分析','<div class="filter"><button class="active">本月</button><button>本周</button><button>本年</button><button>自定义</button></div><div class="page-card"><span>本月支出</span><div class="metric">'+cash(expense)+'</div><div class="bar"><span style="width:62%"></span></div><p class="subtle">收入 '+cash(income)+'　结余 '+cash(income-expense)+'</p></div><h3>支出分类</h3><div class="list-row"><span>🍚</span><span>餐饮</span><b>'+cash(expense)+'</b></div><h3>收支趋势</h3><div class="page-card" style="background:#f7f8fa;display:flex;align-items:end;justify-content:space-around;height:180px"><div style="height:70%;width:24px;background:#e7c77c;border-radius:8px"></div><div style="height:43%;width:24px;background:#e7c77c;border-radius:8px"></div><div style="height:85%;width:24px;background:#e7c77c;border-radius:8px"></div><div style="height:35%;width:24px;background:#e7c77c;border-radius:8px"></div><div style="height:60%;width:24px;background:#e7c77c;border-radius:8px"></div></div>');screen.querySelectorAll('.filter button').forEach(b=>b.addEventListener('click',()=>{screen.querySelectorAll('.filter button').forEach(x=>x.classList.remove('active'));b.classList.add('active');statPeriod=b.textContent;message('已切换到'+statPeriod)}))}
function ledger(){const records=[...added,...sample];page('我的账单','<div class="filter"><button class="active">全部</button><button>支出</button><button>收入</button><button>笔记</button></div><div id="ledger-list"></div>');screen.querySelectorAll('.filter button').forEach(b=>b.addEventListener('click',()=>{screen.querySelectorAll('.filter button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.textContent;renderLedgerList()}));renderLedgerList()}
function renderLedgerList(){const root=document.querySelector('#ledger-list');if(!root)return;const records=[...added,...sample].filter(r=>filter==='全部'||r.type===({支出:'expense',收入:'income',笔记:'note'}[filter]));root.innerHTML=records.map((r,i)=>'<button class="list-row" style="width:100%;border:0;border-bottom:1px solid #eee;background:white;text-align:left" data-id="'+esc(r.id)+'"><span>'+esc(r.time)+'</span>'+categoryPill(r)+'<b>'+(r.type==='note'?'':(r.type==='income'?'+':'−')+cash(r.amount))+'</b></button>').join('')||'<div class="empty">暂无记录</div>';root.querySelectorAll('[data-id]').forEach(el=>el.addEventListener('click',()=>detail(records.find(r=>r.id===el.dataset.id))))}
function search(){page('搜索','<input class="page-input" id="search-input" aria-label="搜索账单" placeholder="搜索账单、备注或分类" value="'+esc(searchText)+'"><div id="search-results"></div>');const inp=document.querySelector('#search-input');inp.addEventListener('input',e=>{searchText=e.target.value;renderSearch()});renderSearch();inp.focus()}
function renderSearch(){const root=document.querySelector('#search-results');if(!root)return;const records=[...added,...sample].filter(r=>searchText&&(r.category+r.note+r.account).includes(searchText));root.innerHTML=records.map(r=>'<button class="list-row" style="width:100%;background:#fff;border:0;border-bottom:1px solid #eee" data-id="'+esc(r.id)+'">'+categoryPill(r)+'<b>'+esc(r.note||cash(r.amount))+'</b></button>').join('')||(searchText?'<div class="empty">没有找到相关记录</div>':'<div class="empty">输入关键词查找记录</div>');root.querySelectorAll('[data-id]').forEach(el=>el.addEventListener('click',()=>detail([...added,...sample].find(r=>r.id===el.dataset.id))))}
function detail(record){selectedRecord=record;go('detail')}
function detailPage(){const r=selectedRecord||sample[0];page('账单详情','<div class="page-card" style="text-align:center;background:#f7f8fa"><div>'+categoryPill(r)+'</div><div class="metric">'+(r.type==='income'?'+':r.type==='note'?'':'−')+(r.type==='note'?'笔记':cash(r.amount))+'</div></div><div class="detail-line"><span>时间</span><b>'+esc(r.date)+' '+esc(r.time)+'</b></div><div class="detail-line"><span>账本</span><b>总账本</b></div><div class="detail-line"><span>账户</span><b>'+esc(r.account||'未选择')+'</b></div><div class="detail-line"><span>备注</span><b>'+esc(r.note||'无')+'</b></div>'+(r.location?'<div class="detail-line"><span>位置</span><b>'+esc(r.location)+'</b></div>':''))}
function note(){screen.innerHTML='<img class="art" src="./assets/home.png" alt="首页背景"><div class="splash" style="background:#0008"></div><div class="note-sheet"><div class="note-title"><input id="note-heading" aria-label="笔记标题" placeholder="给笔记起个标题"><button id="return-entry">⇄ 手动记账</button></div><textarea id="note-text" aria-label="笔记内容" placeholder="记录此刻的想法..."></textarea><div class="note-actions"><span>▤　▧　◎　♧　⌗　▦</span><button id="save-note" aria-label="完成笔记">↑</button></div></div>';document.querySelector('#return-entry').addEventListener('click',()=>go('entry'));document.querySelector('#save-note').addEventListener('click',()=>{const title=document.querySelector('#note-heading').value.trim(),body=document.querySelector('#note-text').value.trim();if(!title&&!body){message('请填写笔记');return}const d=new Date();added.unshift({id:'note-'+Date.now(),type:'note',category:'笔记',amount:0,note:[title,body].filter(Boolean).join('：'),date:today(),time:[d.getHours(),d.getMinutes()].map(v=>String(v).padStart(2,'0')).join(':')});localStorage.setItem(storeKey,JSON.stringify(added));scene='home';render();message('记录成功')})}

function simple(target){
 const labels={calendar:'记录日历',budget:'月预算',voice:'语音记账',profile:'个人信息',auto:'自动记账',transfer:'导入导出',assets:'我的资产',categories:'分类管理',items:'我的物品',community:'社区公约',about:'关于我们',settings:'设置',accounts:'选择账户',ledgers:'选择账本'};
 const title=labels[target]||target;
 if(target==='calendar'){const dates=Array.from({length:30},(_,i)=>i+1);page(title,'<div class="page-card" style="background:#fff"><h2>2025年09月</h2><div style="display:grid;grid-template-columns:repeat(7,1fr);gap:8px;text-align:center;color:#777"><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span><span>日</span>'+dates.map(d=>'<button class="light" data-day="'+d+'">'+d+'</button>').join('')+'</div></div><h3>记录</h3><p class="subtle" id="selected-date">点击日期查看当天记录</p>');screen.querySelectorAll('[data-day]').forEach(btn=>btn.addEventListener('click',()=>{screen.querySelector('#selected-date').textContent='9月'+btn.dataset.day+'日 · '+(added.filter(r=>r.date==='2025-09-'+String(btn.dataset.day).padStart(2,'0')).length||'暂无')+'条记录'}));return}
 if(target==='accounts'){page(title,'<h3>选择记账账户</h3>'+['支付宝','微信支付','现金','银行卡'].map(x=>'<button class="list-row" data-account="'+x+'" style="width:100%;border:0;border-bottom:1px solid #eee;background:#fff;text-align:left">▣　'+x+'<b>›</b></button>').join(''));screen.querySelectorAll('[data-account]').forEach(b=>b.addEventListener('click',()=>{entryAccount=b.dataset.account;scene='entry';render();message('已选择'+entryAccount)}));return}
 if(target==='ledgers'){page(title,'<h3>我的账本</h3><button class="list-row" id="ledger-choice" style="width:100%;border:0;background:white;text-align:left">▤　默认账本<b>✓</b></button>');screen.querySelector('#ledger-choice').addEventListener('click',()=>{scene='entry';render()});return}
 if(target==='budget'){page(title,'<div class="page-card"><span>月预算</span><div class="metric">¥26,517.00</div><span class="subtle">已使用 12%</span><div class="bar" style="margin-top:12px"><span style="width:12%"></span></div></div><div class="list-row">今日可用<b>¥600.00</b></div><div class="list-row">本月结余<b>¥475.00</b></div>');return}
 if(target==='assets'){page(title,'<div class="page-card"><span>总资产</span><div class="metric">¥0.00</div></div><h3>账户</h3><div class="list-row">现金<b>¥0.00</b></div><div class="list-row">银行卡<b>¥0.00</b></div>');return}
 if(target==='categories'){page(title,'<h3>支出分类</h3><div class="list-row">🍚　餐饮</div><div class="list-row">🍦　零食</div><div class="list-row">🍎　水果</div><div class="list-row">🧋　饮品</div><div class="list-row">🥦　做饭食材</div>');return}
 if(target==='settings'){page(title,'<div class="list-row">记账提醒<b>›</b></div><div class="list-row">账本管理<b>›</b></div><div class="list-row">分类管理<b>›</b></div><div class="list-row">关于我们<b>›</b></div>');screen.querySelectorAll('.list-row').forEach((el,i)=>el.addEventListener('click',()=>go(['auto','ledgers','categories','about'][i])));return}
 if(target==='voice'){page(title,'<div style="text-align:center;padding-top:130px"><div style="font-size:56px">◉</div><h2>语音记账</h2><p class="subtle">说出一笔收支，快速记录</p><button class="primary" id="voice-start">开始语音记账</button></div>');screen.querySelector('#voice-start').addEventListener('click',()=>message('当前浏览器未开启麦克风'));return}
 if(target==='auto'){page(title,'<div class="page-card" style="background:#f7f8fa"><h3>自动记账</h3><p>开启后可自动识别账单</p><label><input type="checkbox" id="auto-toggle"> 开启自动记账</label></div>');screen.querySelector('#auto-toggle').addEventListener('change',e=>message(e.target.checked?'已开启':'已关闭'));return}
 if(target==='transfer'){page(title,'<h3>账单数据</h3><button class="list-row" id="export-json" style="width:100%;background:#fff;border:0;border-bottom:1px solid #eee">导出账单数据<b>↓</b></button><p class="subtle">本地演示记录可导出为 JSON 文件。</p>');screen.querySelector('#export-json').addEventListener('click',()=>{const blob=new Blob([JSON.stringify([...added,...sample],null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='小黑记账-演示账单.json';a.click();URL.revokeObjectURL(url)});return}
 if(target==='items'){page(title,'<div class="empty">暂无物品记录</div><div style="text-align:center"><button class="primary" id="item-add">添加物品</button></div>');screen.querySelector('#item-add').addEventListener('click',()=>message('物品信息可在正式应用中添加'));return}
 if(target==='profile'){page(title,'<div class="page-card" style="background:#f7f8fa"><div style="font-size:36px">😎</div><h2>超长昵称样式超长昵称...</h2></div><div class="list-row">个人资料<b>›</b></div>');return}
 if(target==='community'){page(title,'<h2>社区公约</h2><p>友善分享，尊重每一位用户的记录与表达。</p>');return}
 page(title,'<div class="page-card" style="background:#f7f8fa"><h2>小黑记账</h2><p>轻松记录每一笔收支</p></div>')}

function render(){device.classList.toggle('drawer-fit',scene==='drawer');if(scene==='home')onHome();else if(scene==='drawer')onDrawer();else if(scene==='entry')onEntry();else if(scene==='category')categoryExpanded();else if(scene==='stats')stats();else if(scene==='ledger')ledger();else if(scene==='search')search();else if(scene==='detail')detailPage();else if(scene==='note')note();else simple(scene)}
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&scene!=='home'){scene='home';render()}});
render();
