// Reference-matched menu destinations and device-local preferences.
const refinementRender=render;
let preferences=savedJSON('xiaohei-preferences-v1',{mode:'记账模式',sound:true,vibration:true,startDay:1});
let feedbackHistory=savedJSON('xiaohei-feedback-history-v1',[]);
function savePreferences(){localStorage.setItem('xiaohei-preferences-v1',JSON.stringify(preferences))}
function refRow(label,value,id,icon='note'){return '<button class="reference-row" id="'+id+'">'+drawerIcon(icon)+'<span>'+label+'</span><small>'+value+'</small><i>›</i></button>'}
function settingsPage(){livePage('设置','<section class="reference-card">'+refRow('默认模式',esc(preferences.mode),'setting-mode','note')+['sound','vibration'].map((k,i)=>'<div class="reference-row">'+drawerIcon(i?'items':'auto')+'<span>'+['音效','震动'][i]+'</span><button class="reference-switch" role="switch" aria-label="'+['音效','震动'][i]+'" aria-checked="'+preferences[k]+'" data-pref="'+k+'"></button></div>').join('')+refRow('密码保护','','setting-password','wallet')+refRow('当前账本起始日期','每月'+preferences.startDay+'日','setting-period','clock')+'</section><section class="reference-card">'+refRow('清除缓存','0MB','setting-cache','items')+refRow('意见反馈','','setting-feedback','feedback')+refRow('关于我们','','setting-about','note')+'</section><section class="reference-card">'+refRow('删除所有历史账单数据','删除','setting-delete','transfer')+'</section>','','reference-settings');stickyUpdate();screen.querySelectorAll('[data-pref]').forEach(b=>b.onclick=()=>{preferences[b.dataset.pref]=!preferences[b.dataset.pref];savePreferences();b.setAttribute('aria-checked',preferences[b.dataset.pref])});screen.querySelector('#setting-mode').onclick=modeSheet;screen.querySelector('#setting-period').onclick=periodSheet;screen.querySelector('#setting-feedback').onclick=()=>go('feedback');screen.querySelector('#setting-about').onclick=()=>information('关于我们','小黑记账 · 让记录成为习惯');screen.querySelector('#setting-cache').onclick=()=>message('缓存已清理，账单与资料已保留');screen.querySelector('#setting-password').onclick=()=>information('密码保护','当前网页演示未连接账号密码保护服务。');screen.querySelector('#setting-delete').onclick=()=>information('删除所有历史账单数据','此操作会删除账单。当前页面仅演示设置样式，未执行删除。')}
function referenceSheet(title,content){const el=document.createElement('div');el.className='modal-layer reference-sheet-layer';el.innerHTML='<section class="reference-sheet" role="dialog" aria-modal="true" aria-label="'+title+'"><div class="sheet-grip"></div><h2>'+title+'</h2>'+content+'</section>';screen.append(el);el.onclick=e=>{if(e.target===el)el.remove()};return el}
function modeSheet(){const el=referenceSheet('默认模式','<div class="mode-options">'+['记账模式','笔记模式'].map((m,i)=>'<button data-mode="'+m+'" aria-pressed="'+(preferences.mode===m)+'"><b>'+m+'</b><div class="mode-preview">'+sprite({file:'ref-mode-options.jpg',w:1280,h:2774,x:i?960:340,y:2190,size:500},140)+'</div><span class="mode-check">'+(preferences.mode===m?'✓':'')+'</span></button>').join('')+'</div>');el.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{preferences.mode=b.dataset.mode;savePreferences();el.remove();settingsPage()})}
function periodSheet(){const el=referenceSheet('月度周期起始日','<p>设置每个周期的开始日期，修改后会影响统计、预算和报表</p><div class="period-picker"><select aria-label="周期起始日">'+Array.from({length:28},(_,i)=>'<option value="'+(i+1)+'" '+(preferences.startDay===i+1?'selected':'')+'>'+(i+1)+'号</option>').join('')+'</select><div class="period-neighbor"></div><div class="period-neighbor second"></div></div><p class="period-current">当前月度周期：<span></span></p><div class="sheet-actions"><button id="period-cancel">取消</button><button id="period-save">确定</button></div>');const select=el.querySelector('select'),sync=()=>{const now=new Date(),d=Number(select.value),start=new Date(now.getFullYear(),now.getMonth()-(now.getDate()<d?1:0),d),end=new Date(start.getFullYear(),start.getMonth()+1,d-1);el.querySelector('.period-current span').textContent=(start.getMonth()+1)+'月'+d+'日-'+(end.getMonth()+1)+'月'+end.getDate()+'日'};const updateWheel=()=>{sync();const d=Number(select.value);el.querySelector('.period-neighbor').textContent=(d%28+1)+'号';el.querySelector('.period-neighbor.second').textContent=((d+1)%28+1)+'号'};select.onchange=updateWheel;updateWheel();el.querySelector('#period-cancel').onclick=()=>el.remove();el.querySelector('#period-save').onclick=()=>{preferences.startDay=Number(select.value);savePreferences();el.remove();settingsPage()}}
function referenceInviteIcon(){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><circle cx="9" cy="6" r="4"/><path d="M2 22v-4a7 7 0 0 1 13-3M19 13v9M15 17h8"/></svg>'}
function invitationPage(){livePage('我的邀请','<div class="reference-invite-empty">'+sprite({file:'ref-invitation.jpg',w:1280,h:2774,x:640,y:710,size:460},142)+'<p>暂无邀请记录，点击邀请好友吧</p><button class="reference-dark" id="invite-main">'+referenceInviteIcon()+'<span>邀请</span></button></div>','<button id="invite-header" aria-label="邀请好友">'+referenceInviteIcon()+'</button>','reference-invite');stickyUpdate();screen.querySelectorAll('#invite-main,#invite-header').forEach(b=>b.onclick=()=>information('邀请好友','当前演示未连接邀请服务，暂不能生成邀请链接。'))}
function feedbackPage(){livePage('意见反馈','<section class="feedback-hero"><h2>意见反馈</h2><p>留下您的建议，帮助我们更好地改进！</p>'+sprite({file:'ref-feedback-new.jpg',w:1280,h:2774,x:1020,y:436,size:350},111)+'</section><form id="reference-feedback"><section class="reference-card feedback-content"><h2><em>*</em> 反馈内容</h2><textarea aria-label="反馈内容" placeholder="请填写10个字以上的内容，以便我们为您提供更好的内容" minlength="10" required></textarea><div class="feedback-photos"><label class="feedback-upload" aria-label="添加反馈图片">＋<input type="file" accept="image/*" multiple></label></div></section><button class="reference-submit" disabled>提交</button></form>','<button id="feedback-history">反馈记录</button>','reference-feedback');stickyUpdate();const form=screen.querySelector('form'),area=form.querySelector('textarea'),submit=form.querySelector('.reference-submit'),files=form.querySelector('input');area.oninput=()=>submit.disabled=area.value.trim().length<10;files.onchange=()=>{form.querySelectorAll('.feedback-photos img').forEach(e=>e.remove());Array.from(files.files).slice(0,3).forEach(f=>{const reader=new FileReader();reader.onload=()=>{const img=document.createElement('img');img.src=reader.result;img.alt='反馈图片';form.querySelector('.feedback-photos').prepend(img)};reader.readAsDataURL(f)})};form.onsubmit=e=>{e.preventDefault();feedbackHistory.unshift({text:area.value.trim(),date:today(),images:Array.from(form.querySelectorAll('.feedback-photos img')).map(x=>x.src)});try{localStorage.setItem('xiaohei-feedback-history-v1',JSON.stringify(feedbackHistory));message('反馈已保存到本设备');feedbackPage()}catch{message('图片太大，请减少图片后重试')}};screen.querySelector('#feedback-history').onclick=()=>{livePage('反馈记录',feedbackHistory.length?feedbackHistory.map(r=>'<article class="reference-card feedback-history"><p>'+esc(r.text)+'</p><small>'+esc(r.date)+' · 已保存到本设备</small></article>').join(''):'<div class="bill-empty">暂无反馈记录</div>','','reference-feedback');stickyUpdate();screen.querySelector('.live-back').onclick=feedbackPage}}
profileEditor=function(){go('profileEditor')};
function aboutYouPage(){const editMark=drawerIcon('edit');livePage('关于你','<div class="profile-editor-avatar"><button aria-label="编辑头像" id="change-avatar">'+drawerAvatar()+'<i>'+editMark+'</i></button><input id="avatar-file" type="file" accept="image/*" hidden></div><section class="reference-card">'+refRow('昵称',esc(profileData.name),'edit-name')+refRow('手机',esc(profileData.phone||'未设置'),'edit-phone')+refRow('微信','未绑定','edit-wechat')+refRow('ID','本设备','copy-id')+'<div class="reference-row"><span>注册时间</span><small>2026-09-18</small></div></section><section class="reference-card">'+refRow('简介',esc(profileData.bio||'介绍一下自己'),'edit-bio')+'</section><section class="reference-card">'+refRow('性别',esc(profileData.gender||'未设置'),'edit-gender')+refRow('生日',esc(profileData.birthday||'未设置'),'edit-birthday')+refRow('月收入',esc(profileData.salary||'未设置'),'edit-salary')+'</section><button class="reference-submit" id="profile-logout">退出登录</button>','<button id="profile-more" aria-label="更多资料选项">'+uiIcon('dots')+'</button>','reference-profile-editor');stickyUpdate();screen.querySelector('.live-back').onclick=back;const edit=(key,title,type='text')=>{const el=referenceSheet(title,'<form class="profile-value-form"><input aria-label="'+title+'" type="'+type+'" value="'+esc(profileData[key]||'')+'" '+(key==='name'?'required maxlength="30"':'')+'><button class="reference-dark">保存</button></form>');el.querySelector('form').onsubmit=e=>{e.preventDefault();profileData[key]=el.querySelector('input').value.trim();localStorage.setItem('xiaohei-profile-v1',JSON.stringify(profileData));el.remove();aboutYouPage()}};[['name','昵称'],['phone','手机'],['bio','简介'],['gender','性别'],['birthday','生日','date'],['salary','月收入','number']].forEach(([key,title,type])=>screen.querySelector('#edit-'+key).onclick=()=>edit(key,title,type));screen.querySelector('#change-avatar').onclick=()=>screen.querySelector('#avatar-file').click();screen.querySelector('#avatar-file').onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{profileData.avatar=reader.result;try{localStorage.setItem('xiaohei-profile-v1',JSON.stringify(profileData));aboutYouPage()}catch{message('图片过大，请选择较小的图片')}};reader.readAsDataURL(f)};screen.querySelector('#edit-wechat').onclick=()=>information('微信','当前网页演示未连接微信绑定服务。');screen.querySelector('#copy-id').onclick=()=>message('当前资料保存在本设备');screen.querySelector('#profile-logout').onclick=()=>information('退出登录','当前使用本设备演示资料，尚未连接登录服务。');screen.querySelector('#profile-more').onclick=()=>information('关于你','资料修改会保存到本设备。')}
const defaultDrawerAvatar=drawerAvatar;
drawerAvatar=function(){return profileData.avatar?'<img class="drawer-avatar" src="'+esc(profileData.avatar)+'" alt="头像">':defaultDrawerAvatar()};
render=function(){const routes={settings:settingsPage,feedback:feedbackPage,invite:invitationPage,profileEditor:aboutYouPage};if(routes[scene])routes[scene]();else refinementRender()};
render();
function settingsIcon(kind){const paths={mode:'<rect x="8" y="3" width="12" height="16" rx="3" transform="rotate(15 14 11)"/><path d="M5 6 2 17q-1 3 3 4l5 1M12 7h5M11 11h5"/>',sound:'<path d="M8 18V5l12-3v13M8 8l12-3"/><circle cx="5" cy="18" r="3"/><circle cx="17" cy="15" r="3"/>',vibration:'<path d="M8 3h8q3 0 3 3v12q0 3-3 3H8q-3 0-3-3V6q0-3 3-3M2 6l-1 3 2 3-2 3 1 3M22 6l1 3-2 3 2 3-1 3"/>',lock:'<rect x="5" y="10" width="14" height="12" rx="4"/><path d="M8 10V6a4 4 0 0 1 8 0v4M12 14v4"/>',calendar:'<rect x="3" y="5" width="18" height="17" rx="4"/><path d="M7 2v6M17 2v6M3 11h18"/>',trash:'<path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7"/>',info:'<circle cx="12" cy="12" r="10"/><path d="M12 6v7M12 17h.01"/>',delete:'<path d="M20 12V7q0-2-2-2h-7L8 2H4q-2 0-2 2v14q0 2 2 2h8M16 16l6 6M22 16l-6 6"/>'};return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+paths[kind]+'</svg>'}
const refinementSettings=settingsPage;
settingsPage=function(){refinementSettings();[['setting-mode','mode'],['setting-password','lock'],['setting-period','calendar'],['setting-cache','trash'],['setting-about','info'],['setting-delete','delete']].forEach(([id,kind])=>screen.querySelector('#'+id+' svg').outerHTML=settingsIcon(kind));screen.querySelector('[data-pref="sound"]').parentElement.querySelector('svg').outerHTML=settingsIcon('sound');screen.querySelector('[data-pref="vibration"]').parentElement.querySelector('svg').outerHTML=settingsIcon('vibration')};
const refinementAboutYou=aboutYouPage;
aboutYouPage=function(){refinementAboutYou();screen.querySelectorAll('#edit-name,#edit-phone,#edit-bio,#edit-gender,#edit-birthday,#edit-salary').forEach(b=>b.querySelector('i').innerHTML=drawerIcon('edit'));screen.querySelector('#copy-id i').innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.3"><rect x="6" y="6" width="15" height="16" rx="3"/><path d="M17 3H5q-2 0-2 2v13"/></svg>'};
